### ISSUE TITLE
Disallow HTML blocks and spans?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/myst_parser#20]
Since we have directives and roles that could make HTML at a block or in-line level explicit (rather than detected with regexes and such), what do folks think about explicitly *not* allowing raw HTML in the myst content, and instead asking people to use a directive or role if they want to embed HTML in their page?

**Comment by chrisjsewell** [comment]
To be compliant with CommonMark, it has to at least detect it anyway, even if it is later ignored. So I don’t see much benefit in disallowing it, although obviously it should be discouraged.

**Comment by choldgraf** [comment]
Yeah - I had the same thought re: breaking spec w/ CommonMark. I think it's a good idea to explicitly discourage it in the docs. I'll ad that in a little PR
