### ISSUE TITLE
Code blocks w/o language raise a warning

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/myst_parser#23]
I keep getting warnings when building the docs, they look like this:

```
Pygments lexer name '' is not known
```

I'm pretty sure this is because of

````
```
some raw text
```
````
blocks with no language specified. Should we default code blocks w/o a language to a default "raw" language with Pygments, so a warning isn't raised?

**Comment by chrisjsewell** [comment]
Agree, should have a dig in to the Sphinx code to see where/how they do this normally

**Comment by choldgraf** [comment]
Could it just be a little check here:

https://github.com/ExecutableBookProject/myst_parser/blob/4f5df007831cb6bff045e844b63c1ed0b1976f9d/myst_parser/block_tokens.py#L266

And

```
language = 'some default language' if (len(open_info[2]) == 0) else open_info[2]
    self.language = language
```

?

Also, here's a PR that seems to alter the default behavior in Sphinx's `code-block` directive:

https://github.com/sphinx-doc/sphinx/pull/6015/files#diff-9e49ca3710206668e9b66660dd700875R474
