### ISSUE TITLE
'$'-delimited in-line math example fails in `syntax.md`

### ISSUE THREAD

**Issue by rossbar** [ExecutableBookProject/myst_parser#51]
The $-delimited math [on line 352 of syntax.md](https://github.com/ExecutableBookProject/myst_parser/blob/develop/docs/using/syntax.md#L352) doesn't render properly at build.

Other instances of $-delimited inline math in the file seem to work though, not sure why this particular instance is not working.

N.B. switching to the myst-role syntax `{math}...` works fine.

**Comment by chrisjsewell** [comment]
Thanks @rossbar I'll look into it

**Comment by rossbar** [comment]
Are bug reports along these lines valuable? I'm in the process of translating some open-source text book material into `myst` format (which is fantastic BTW) for testing and I'm sure I will come across other issues. I can open issues here to keep things centralized, but I don't want to spam the repo with a bunch of potentially-low-priority issues. I'm happy to keep issues in a different repo/fork. LMK your preference!

**Comment by chrisjsewell** [comment]
> Are bug reports along these lines valuable?

Oh yeh they are super useful thanks 😄 

>  I don't want to spam the repo with a bunch of potentially-low-priority issues

If you go to add an issue now you will see options for adding 'Bug Reports' or 'Feature Requests', these will auto categorize the issues etc, so they are easier to deal with. Spam away!

**Comment by chrisjsewell** [comment]
@rossbar this should be fixed in the last commit, but please reopen if you still encounter a problem

**Comment by rossbar** [comment]
@chrisjsewell it appears I can't re-open the issue so I'll just comment: line 365 from `doc/using/syntax.md` is still not properly rendering the in-line, '$'-delimited math in the html as of 1a1cd05

**Comment by chrisjsewell** [comment]
@rossbar actually fixed now!
