### ISSUE TITLE
Inconsistent behavior of 'name' argument in `code-block` directive

### ISSUE THREAD

**Issue by rossbar** [ExecutableBookProject/myst_parser#56]
**Describe the bug**
From limited testing, it appears that the `name: ` argument requires a string to work within the `{code-block}` directive. This is inconsistent with how `name: ` appears to work within other directives such as `{figure}` or `{table}`, for instance.

**To Reproduce** 
The following works for creating a label called `fig:my` that can then be used in the text via the `{ref}` or `{numref}` roles. This works with the table directive as well.
```
​```{figure} my_figure.png
---
name: fig:my
---
​```
```

However, the following fails to define a label (a sphinx warning about an undefined label is raised if you try to reference code:my in the document):

```
​```{code-block} python
---
name: code:my
---
def my_fun(): pass
​```
```

The following works however (note the quotes around the label name):
```
​```{code-block} python
---
name: 'code:my'
---
def my_fun(): pass
​```
```

**Expected behavior**

I am not a sphinx/docutils expert, so maybe this is the expected behavior. However I would expect the `name:` argument to result in consistent behavior within all directives for which it is defined.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Python Version: 3.8.1
 - Package Version: myst_parser@4150051

**Comment by rossbar** [comment]
NVM - the issue I reported is incorrect. The `caption:` must be defined as well within the `code-block` for the `name:` to work.

**Comment by chrisjsewell** [comment]
Always happy when an issue gets closed before I’ve even looked at it 😆

**Comment by rossbar** [comment]
I'm getting a little trigger happy :fearful:
