### ISSUE TITLE
caption: argument fails with backtick

### ISSUE THREAD

**Issue by rossbar** [ExecutableBookProject/myst_parser#57]
**Describe the bug**
Attempting to use a single-line `caption:` argument within the `code-block` results in the following error during sphinx build:
```
home/ross/repos/elegant-scipy/sphinx/content/ch1.md:22: WARNING: Directive options:
while scanning for the next token                                                            
found character '`' that cannot start any token                                              
  in "<unicode string>", line 2, column 18:                                                  
    caption: {numref}`tab:counts` as a `numpy` array
```
Note that this error is avoided by:
 - Placing the caption in quotes: ```caption: 'this will not ​fail {ref}`my:ref`' ```
 - Multiline captions with `|`:
   ```
   caption: |
       This won't fail either {ref}`my:ref`
   ```

**To Reproduce**
Use a backtick in an un-quoted, single-line caption within a code block, e.g.:
````
```{code-block} python
---
name: code:label
caption: Caption with reference to outside figure {ref}`fig`
---
a = 1
```
````

**Expected behavior**
As noted above, there are already (at least) two ways around this problem, so maybe it just needs to be documented. In a perfect world, it would be possible to use backticks in a single-line caption without any additional escaping.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Python Version: 3.8.1
 - Package Version: myst_parser@ccf6a56a

**Additional context**
This was the *real* cause of #56

**Comment by chrisjsewell** [comment]
@rossbar if you could just check this still occurs after the last commit.

**Comment by rossbar** [comment]
Sure - I'm still seeing the same error on 1a1cd05ba

**Comment by chrisjsewell** [comment]
@rossbar its not actually because of the backticks, it is because of the starting `{`
This works fine:

```python
>> import yaml
>> yaml.safe_load("""\
.. name: code:label
.. caption: Caption with reference to outside figure {ref}`fig`
.. """)

{'name': 'code:label',
 'caption': 'Caption with reference to outside figure {ref}`fig`'}
```

However, YAML parses inline dictionaries:

```python
>> yaml.safe_load("""\
.. arg: {a: 1}
.. """)

{'arg': {'a': 1}}
```

So here it tries to do that, and fails:

```python
>> yaml.safe_load("""\
.. name: code:label
.. caption: {numref}`tab:counts` as a `numpy` array
.. """)
```

This is when you need to wrap your string in quotes.

**Comment by chrisjsewell** [comment]
Closing this, since the warning messages are now prefixes by `Invalid YAML`, which I think is sufficient to aid the user in diagnosing the issue, e.g.

```
home/ross/repos/elegant-scipy/sphinx/content/ch1.md:22: WARNING: Directive 'code-block' options:
Invalid YAML: while scanning for the next token                                                            
found character '`' that cannot start any token                                              
  in "<unicode string>", line 2, column 18:                                                  
    caption: {numref}`tab:counts` as a `numpy` array
```

**Comment by rossbar** [comment]
Thanks for looking into it - I agree the descriptive traceback is helpful.
